apiVersion: data.packaging.carvel.dev/v1alpha1
kind: Package
metadata:
  name: pinniped.community.tanzu.vmware.com.0.12.1
spec:
  refName: pinniped.community.tanzu.vmware.com
  version: 0.12.1
  releaseNotes: "pinniped 0.12.1 https://github.com/vmware-tanzu/pinniped/releases/tag/v0.12.1"
  licenses:
    - "Apache 2.0"
  template:
    spec:
      fetch:
        - imgpkgBundle:
            image: projects.registry.vmware.com/tce/pinniped@sha256:fefeea92ad5ebbe0bb6a515ca73ea7982c6522c8f00432402f0e4e6fa6ceda95
      template:
        - ytt:
            paths:
              - config/
        - kbld:
            paths:
              - "-"
              - kbld-config.yaml
              - .imgpkg/images.yml
      deploy:
        - kapp:
            rawOptions: ["--dangerous-allow-empty-list-of-resources=true"]
