#@ load("@ytt:data", "data")

#@ if data.values.identity_management_type != "none":
---
apiVersion: authentication.concierge.pinniped.dev/v1alpha1
kind: JWTAuthenticator
metadata:
  name: tkg-jwt-authenticator
spec:
  audience: #@ data.values.pinniped.supervisor_svc_endpoint
  issuer: #@ data.values.pinniped.supervisor_svc_endpoint
  tls:
    certificateAuthorityData: #@ data.values.pinniped.supervisor_ca_bundle_data
#@ end